title: someet singh # your name (or website title) here
logo: "images/isro_1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 1 years of commercial experience in analytics, strategy and a master's degree in Data Science from Amity university, Noida (CGPA 9.92). 
  <br>
  Currently working as software engineer (AI/ML) at Audax Labs. 
  <br>
  • 1st Place Winner - All India ISRO (Indian Space Research
  Organization) Smart India Hackathon
  2022 (SIH) for the problem Statement “Deep learning-based
  Cyclone intensity Estimation
  using INSAT-3D IR imagery” our solution - “worked on
  providing solution for detecting
  cyclone and estimation of cyclone intensity Also created a web
  app for the same.
  <br>
  <a href="https://www.linkedin.com/in/someetsingh/">View my LinkedIn Profile</a> 
  <br>
  <a href="https://drive.google.com/file/d/17Cd7Slrcsrt1LlOc-OmA9pOleolldDiw/view?usp=sharing">View my Resume</a> 
  <br>
  <a href="https://github.com/Aesthethic0de">View my Github Profile</a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
